server:
  port: 8080
  #undertow:
    #threads:
     # io: 6
      #worker: 500
    #buffer-size: 1024
    #direct-buffers: true
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.148:8848
        group: spring-cloud
        ip: localhost
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        response-timeout: 3000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
