server:
  port: 0
spring:
  application:
    name: orderservice
  cloud:
    nacos:
      discovery:
        group: spring-cloud
        server-addr: 192.168.50.140:8848
        ip: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS